Repository heremaps/harp.gl, pull requests merged in 2020-12, with the labels that each got.

#1980 HARP-12581: Fix render order for labels
  @here/harp-mapview/lib/geometry/TileGeometryCreator.ts
  @here/harp-mapview/lib/poi/PoiManager.ts
  @here/harp-mapview/lib/text/TextElement.ts
  @here/harp-mapview/lib/text/TextElementBuilder.ts
  @here/harp-mapview/test/TextElementBuilderTest.ts
  test/rendering/GeoJsonDataRendering.ts
  test/rendering/utils/GeoJsonTest.ts
Labels: topic:HARP-12581_Labels

#1991 HARP-13251: Add support for wrapping linestrings crossing the antimeridian.
  @here/harp-geometry/lib/ClipLineString.ts
  @here/harp-geometry/lib/WrapLineString.ts
  test/rendering/GeoJsonDataRendering.ts
Labels: topic:wrap-linestrings

#1999 HARP-13084: Add karma.options.js
  karma.conf.js
  karma.options.js
Labels: topic:HARP-13084

#1994 HARP-12677: Extract PoiRenderer from TextCanvas
  @here/harp-mapview/lib/MapView.ts
  @here/harp-mapview/lib/poi/PoiRenderer.ts
  @here/harp-mapview/lib/poi/PoiRendererFactory.ts
  @here/harp-mapview/lib/text/FontCatalogLoader.ts
  @here/harp-mapview/lib/text/TextCanvasFactory.ts
  @here/harp-mapview/lib/text/TextCanvasRenderer.ts
  @here/harp-mapview/lib/text/TextElementsRenderer.ts
  @here/harp-mapview/lib/text/TextStyleCache.ts
  @here/harp-mapview/test/PoiBatchRegistryTest.ts
  @here/harp-mapview/test/PoiInfoBuilder.ts
  @here/harp-mapview/test/TextElementsRendererTestFixture.ts
  @here/harp-mapview/test/stubPoiRenderer.ts
  @here/harp-text-canvas/lib/TextCanvas.ts
  test/rendering/GeoJsonDataRendering.ts
Labels: topic:poi-renderer

#2003 Upgrade highlight.js
  @here/harp-examples/package.json
  yarn.lock
Labels: topic:highlightjs-upgrade

#2004 Run yarn-deduplicate on yarn.lock
  yarn.lock
Labels: topic:highlightjs-upgrade

#2002 Makes TextElementsRenderer update- and reset-able
  test/rendering/GeoJsonDataRendering.ts
  test/rendering/GeoJsonFeaturesRendering.ts
  test/rendering/ScreenSpaceRenderingTests.ts
  test/rendering/utils/GeoJsonTest.ts
  test/rendering/utils/ThemeBuilder.ts
Labels: topic:textelementsrenderer-refactor

#2006 Remove duplicate readdirp from the yarn lockfile.
  yarn.lock
Labels: topic:readdirp-duplicates

#1917 HARP-12728: Add support for webpack5
  .travis.yml
  @here/harp-examples/package.json
  @here/harp-examples/webpack.config.js
  @here/harp-mapview/test/MapViewTest.ts
  @here/harp-mapview/test/ThemeLoaderTest.ts
  @here/harp-webpack-utils/package.json
  @here/harp-webpack-utils/scripts/HarpWebpackConfig.ts
  @here/harp.gl/package.json
  @here/harp.gl/webpack.config.js
  package.json
  test/README.md
  webpack.tests.config.js
  www/package.json
  www/webpack.config.js
  yarn.lock
Labels: topic:HARP-12623

#2010 HARP-13367: Update Three JS (0.123.0)
  @here/harp-datasource-protocol/package.json
  @here/harp-debug-datasource/package.json
  @here/harp-examples/package.json
  @here/harp-features-datasource/package.json
  @here/harp-geojson-datasource/package.json
  @here/harp-geometry/package.json
  @here/harp-geoutils/package.json
  @here/harp-lines/lib/HighPrecisionLines.ts
  @here/harp-lines/lib/HighPrecisionPoints.ts
  @here/harp-lines/package.json
  @here/harp-map-controls/package.json
  @here/harp-mapview/lib/MapView.ts
  @here/harp-mapview/lib/Utils.ts
  @here/harp-mapview/lib/geometry/SolidLineMesh.ts
  @here/harp-mapview/package.json
  @here/harp-mapview/test/SolidLineMeshTest.ts
  @here/harp-materials/lib/GroundAtmosphereMaterial.ts
  @here/harp-materials/lib/SkyAtmosphereMaterial.ts
  @here/harp-materials/package.json
  @here/harp-omv-datasource/package.json
  @here/harp-test-utils/package.json
  @here/harp-text-canvas/package.json
  @here/harp-vectortile-datasource/package.json
  @here/harp-webtile-datasource/package.json
  @here/harp.gl/package.json
  package.json
  test/performance/package.json
  test/rendering/package.json
  www/package.json
  yarn.lock
Labels: topic:HARP-13367

#2011 HARP-12728: Update Webpack's MiniCssExtractPlugin.
  www/package.json
  yarn.lock
Labels: topic:HARP-12728_UpdateMiniCssPlugin

#2008 TextElementsRenderer supports Font and TextStyle updates
  @here/harp-mapview/lib/MapView.ts
  @here/harp-mapview/lib/MapViewThemeManager.ts
  @here/harp-mapview/lib/text/FontCatalogLoader.ts
  @here/harp-mapview/lib/text/Placement.ts
  @here/harp-mapview/lib/text/TextElementsRenderer.ts
  @here/harp-mapview/lib/text/TextElementsRendererOptions.ts
  @here/harp-mapview/lib/text/TextStyleCache.ts
  @here/harp-mapview/test/MapViewTest.ts
  @here/harp-mapview/test/TextElementsRendererTest.ts
  @here/harp-mapview/test/TextElementsRendererTestFixture.ts
  @here/harp-mapview/test/stubFontCatalogLoader.ts
  @here/harp-mapview/test/stubTextCanvas.ts
  @here/harp-text-canvas/test/rendering/TextCanvasRenderingTest.ts
  @here/harp-vectortile-datasource/test/MapViewPickingTest.ts
Labels: topic:textelementsrenderer-refactor

#2015 MINOR: Removes default font catalog option
  @here/harp-mapview/lib/text/TextElementsRenderer.ts
  @here/harp-mapview/lib/text/TextElementsRendererOptions.ts
  @here/harp-mapview/lib/text/TextStyleCache.ts
  @here/harp-mapview/test/TextElementsRendererTestFixture.ts
Labels: topic:remove-default-font
